[package]
name = "stakataka"
version = "0.1.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "^0.4.10"
#mopa = "^0.2.2"
#objekt = "^0.1.2"
