[package]
name = "tiketetaketitak"
version = "0.1.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "^0.4.10"
strum = "^0.15.0"
strum_macros = "^0.15.0"
